server:
  port: 8083

spring:
  application:
    name: notification-service
  config:
    import: optional:nacos:notification-service.yaml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: DEFAULT_GROUP
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        file-extension: yaml
        namespace: ${NACOS_NAMESPACE:dev}
        group: DEFAULT_GROUP

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# 自定义配置
app:
  name: "通知服务"
  version: "1.0.0"
  description: "提供消息通知功能"

logging:
  level:
    com.example.notification: ${LOGGING_LEVEL_ROOT:INFO}
