apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: microservices
type: Opaque
data:
  # 数据库凭据 (base64编码)
  username: c3ByaW5nX3VzZXI=  # spring_user
  password: c3ByaW5nX3Bhc3M=  # spring_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: nacos
type: Opaque
data:
  # MySQL凭据用于Nacos (base64编码)
  username: bmFjb3M=      # nacos
  password: bmFjb3MxMjM=  # nacos123
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
data:
  # 应用密钥 (base64编码)
  jwt.secret: bXlfc2VjcmV0X2tleV9mb3Jfand0X3Rva2Vu  # my_secret_key_for_jwt_token
  encryption.key: YWVzX2VuY3J5cHRpb25fa2V5XzEyMw==      # aes_encryption_key_123
