server:
  port: 8082

spring:
  application:
    name: order-service
  config:
    import: optional:nacos:order-service.yaml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: DEFAULT_GROUP
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        file-extension: yaml
        namespace: ${NACOS_NAMESPACE:dev}
        group: DEFAULT_GROUP
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Feign 配置
feign:
  circuitbreaker:
    enabled: true

# 自定义配置
app:
  name: "订单服务"
  version: "1.0.0"
  description: "提供订单管理功能"

logging:
  level:
    com.example.order: ${LOGGING_LEVEL_ROOT:INFO}
